In [1]:
import tensorflow as tf

In [2]:
rand = tf.random.uniform([1], 0, 1)
rand
# 출력값 : <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.40041852], dtype=float32)>
# Tensor 라는 객체 반환
# Tensor 참조 문서 : https://www.tensorflow.org/api_docs/python/tf/Tensor
# shape : Numpy 배열의 크기
# tensorflow의 data type 참조 문서 : https://www.tensorflow.org/api_docs/python/tf/dtypes/DType

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7900951], dtype=float32)>

In [3]:
rand2 = tf.random.uniform([1], 0, 1, dtype=tf.dtypes.float64)  # 균일분포
                                                               # dtype 지정 가능
rand2

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.62903476])>

In [4]:
rand3 = tf.random.uniform([4], 0, 1, dtype=tf.dtypes.float64)
rand3

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.9202414 , 0.93086986, 0.93180397, 0.16154772])>

In [5]:
rand3 = tf.random.uniform([2,2], 0, 1, dtype=tf.dtypes.float64)
rand3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.02668646, 0.18663054],
       [0.84789366, 0.97926003]])>

In [6]:
rand2.shape

TensorShape([1])

In [7]:
rand2.dtype

tf.float64

In [8]:
rand2.ndim

1

In [9]:
rand3.ndim

2

In [10]:
rand = tf.random.normal([2,2], 0, 1)  # 정규분포
rand

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.679577  ,  0.9739455 ],
       [ 2.481045  , -0.42814425]], dtype=float32)>

In [11]:
rand2 = tf.random.normal([4], 10, 2)
rand2

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([10.6838665,  4.329226 , 13.134554 ,  9.815259 ], dtype=float32)>

In [12]:
# 활성화함수 sigmoid 정의
import math
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

In [13]:
# 3.11 뉴런의 입력과 출력 정의
x = 1  # 입력
y = 0  # 기대출력
w = tf.random.normal([1], 0, 1)  # 입력의 가중치
output = sigmoid(x * w)
print(output)  # 출력

0.2814401647917762


In [14]:
y - output  # 오류 = 기대출력 - 출력

-0.2814401647917762

In [15]:
# 3.12 경사하강법을 이용한 뉴런의 학습
x = 1
y = 0
w = tf.random.normal([1], 0, 1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error  # 학습률 = 0.1
    
    if i % 100 == 99:
        print(i, error, output)
# 0.12에서 0.01까지 내려감
# 예측출력 0에 가까워짐

99 -0.08988775145368233 0.08988775145368233
199 -0.04878003726786652 0.04878003726786652
299 -0.033202194205919904 0.033202194205919904
399 -0.0250977091016917 0.0250977091016917
499 -0.02014887266030027 0.02014887266030027
599 -0.016819268075775537 0.016819268075775537
699 -0.014428433175174038 0.014428433175174038
799 -0.012629580528800016 0.012629580528800016
899 -0.011227624341879263 0.011227624341879263
999 -0.010104613912926661 0.010104613912926661


In [16]:
# 3.13 x = 0, y = 1일 때의 경사하강법을 이용한 뉴런의 학습
x = 0
y = 1
w = tf.random.normal([1], 0, 1)

for i in range(1000):
    output = sigmoid(x * w)
    error = y - output
    w = w + x * 0.1 * error  # 학습률 = 0.1
    
    if i % 100 == 99:
        print(i, error, output)

# x = 0이므로 error값, w값이 변화하지 않음.
# 뉴런이 학습을 하지 못함.
# 한쪽으로 치우쳐진 상황임

# 해결방법 : 편향(bias)값을 줌.

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


In [17]:
# 3.14. x = 0, y = 0, 편향 추가
x = 0
y = 1
w = tf.random.normal([1], 0, 1)
b = tf.random.normal([1], 0, 1)  # bias(편향) 추가

for i in range(1000):
    output = sigmoid(x * w + 1 * b)  # 편향의 입력으로는 보통 1 사용
    error = y - output
    w = w + x * 0.1 * error
    b = b + 1 * 0.1 * error
    
    if i % 100 == 99:
        print(i, error, output)
# 0.89에서 0.99까지 올라감
# 예측출력 1에 가까워짐

99 0.12250498884498218 0.8774950111550178
199 0.057557198467882986 0.942442801532117
299 0.03712497894320144 0.9628750210567986
399 0.02729720777651856 0.9727027922234814
499 0.02155016907954277 0.9784498309204572
599 0.017788128068461417 0.9822118719315386
699 0.015137487339494715 0.9848625126605053
799 0.01317052438459898 0.986829475615401
899 0.011653741125976613 0.9883462588740234
999 0.010448827586676424 0.9895511724133236


In [18]:
# 3.16 첫 번째 신경망 네트워크 : AND
import numpy as np
x = np.array([   # 입력값
    [1, 1],
    [1, 0],
    [0, 1],
    [0, 0]
])
y = np.array([   # 기대출력
    [1],
    [0],
    [0],
    [0] 
])
w = tf.random.normal([2], 0, 1)  # 입력값의 가중치
                                 # 입력1, 입력2 -> 2개니까 가중치도 각각해서 총 2개
b = tf.random.normal([1], 0, 1)  # 편향(bias)
b_x = 1                          # 편향의 입력값
alpha = 0.1                      # 학습률

for i in range(2000):  # 학습수 : 2000번
    error_sum = 0
    for j in range(4): # 한 번 학습할 때마다 데이터 4개를 입력하니까
        output =  sigmoid(np.sum(x[j] * w) + b_x * b)  # 입력값 * 가중치를 다 더함
                                                       # 데이터 4개 + 편향 전체의 (입력값 * 가중치)의 합
                                                       # 참고) numpy의 ndarray는 *할 때 shape에 맞게 알아서 조절이 된다.
        error = y[j][0] - output  # 오차값 = 기대출력 - 출력
        
        # 경사하강법에 의한 가중치, 편향의 조정
        w = w + x[j] * alpha * error
        b = b + b_x * alpha * error
        error_sum += error                             # 데이터별로 error 나오니까 데이터 4개의 에러총 합이 학습 1번할때마다의 오류
    if i % 200 == 199:
        print(i, error_sum)
# print(x[0])  # [1 1]
# print(x[1])  # [1 0]
# print(x[2])  # [0 1]
# print(x[3])  # [0 0]
# print(w)  # 만약 [1.02~ 0.85~] 라면
# print(x[0] * w)  # [1 1] * [1.02~ 0.85~] = [1.02~ 0.85~]
# print(x[1] * w)  # [1 0] * [1.02~ 0.85~] = [1.02~ 0.]
# print(x[0] * w + x[1] * w + x[2] * w + x[3] * w + b_x * b)  # 각각의 입력값 * 가중치를 다 더한게 output. 출력값.

199 -0.10732952767638354
399 -0.06464610390439707
599 -0.046131692197569255
799 -0.035759046362695425
999 -0.02914236243602561
1199 -0.02456404306939842
1399 -0.0212134978076773
1599 -0.018657838730796544
1799 -0.01664470253276492
1999 -0.015019130318228305


In [19]:
# AND 신경망 네트워크 평가
# 학습 2000번 시킨 후의 결과로 평가
for i in range(4):
    print("X:", x[i], "Y:", y[i], "Output:", sigmoid(np.sum(x[i] * w) + b_x * b))

X: [1 1] Y: [1] Output: 0.9649359755836532
X: [1 0] Y: [0] Output: 0.024848036424332202
X: [0 1] Y: [0] Output: 0.02492386267145816
X: [0 0] Y: [0] Output: 2.3667358365141617e-05


In [20]:
# 3.21 두 번째 신경망 네트워크 : OR
x = np.array([
    [1, 1],
    [1, 0],
    [0, 1],
    [0, 0]
])
y = np.array([
    [1],
    [1],
    [1],
    [0]
])
w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1
alpha = 0.1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        
        # 경사하강법에 의한 가중치, 편향의 조정
        w = w + x[j] * alpha * error
        b = b + b_x * alpha * error
        
        error_sum += error
    if i % 200 == 199:
        print(i, error_sum)

199 -0.04495503624295849
399 -0.024346006885461305
599 -0.016663041929525987
799 -0.012632437155711683
999 -0.010156128870869204
1199 -0.008483337966036786
1399 -0.007279484354753771
1599 -0.006371815786535742
1799 -0.00566463047676094
1999 -0.005096254555767867


In [21]:
# OR 신경망 네트워크 평가
# 학습 2000번 시킨 후의 결과로 평가
for i in range(4):
    print("X:", x[i], "Y:", y[i], "Output:", sigmoid(np.sum(x[i] * w) + b_x * b))

X: [1 1] Y: [1] Output: 0.9999972920472859
X: [1 0] Y: [1] Output: 0.9898734607168455
X: [0 1] Y: [1] Output: 0.9898928769856092
X: [0 0] Y: [0] Output: 0.025270064526535845


In [22]:
# 3.23 세 번째 신경망 네트워크 : XOR
x = np.array([
    [1, 1],
    [1, 0],
    [0, 1],
    [0, 0]
])
y = np.array([
    [0],
    [1],
    [1],
    [0]
])
w = tf.random.normal([2], 0, 1)
b = tf.random.normal([1], 0, 1)
b_x = 1
alpha = 0.1

for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmoid(np.sum(x[j] * w) + b_x * b)
        error = y[j][0] - output
        
        w = w + x[j] * 0.1 * error
        b = b + b_x * 0.1 * error
        
        error_sum += error
    
    if i % 200 == 199:
        print(i, error_sum)

199 -0.001598492994095535
399 -6.499538410842387e-05
599 -2.6460087578783487e-06
799 -1.3774515783548935e-07
999 3.722842145670313e-09
1199 3.722842145670313e-09
1399 3.722842145670313e-09
1599 3.722842145670313e-09
1799 3.722842145670313e-09
1999 3.722842145670313e-09


In [23]:
# XOR 신경망 네트워크 평가
# 학습 2000번 시킨 후의 결과로 평가
for i in range(4):
    print("X:", x[i], "Y:", y[i], "Output:", sigmoid(np.sum(x[i] * w) + b_x * b))

X: [1 1] Y: [0] Output: 0.5128176286712095
X: [1 0] Y: [1] Output: 0.5128176305326305
X: [0 1] Y: [1] Output: 0.4999999990686774
X: [0 0] Y: [0] Output: 0.5000000009313226
